// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM717y_Q9GXXqljQOyJA1-oTQPpI8ae3I',
    appId: '1:908937894285:web:5f6b32307a2c8a84d385c4',
    messagingSenderId: '908937894285',
    projectId: 'tech-news-aggregator-a565b',
    authDomain: 'tech-news-aggregator-a565b.firebaseapp.com',
    storageBucket: 'tech-news-aggregator-a565b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDntJ4rzACgughdoqeGZBR0yDVvIPM1UU8',
    appId: '1:908937894285:android:00955a929a9c187ed385c4',
    messagingSenderId: '908937894285',
    projectId: 'tech-news-aggregator-a565b',
    storageBucket: 'tech-news-aggregator-a565b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0XAkHke3IvlRc77GKypBG_BA54anVaqo',
    appId: '1:908937894285:ios:57a79e3ce250ac7bd385c4',
    messagingSenderId: '908937894285',
    projectId: 'tech-news-aggregator-a565b',
    storageBucket: 'tech-news-aggregator-a565b.firebasestorage.app',
    iosBundleId: 'com.example.techsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0XAkHke3IvlRc77GKypBG_BA54anVaqo',
    appId: '1:908937894285:ios:57a79e3ce250ac7bd385c4',
    messagingSenderId: '908937894285',
    projectId: 'tech-news-aggregator-a565b',
    storageBucket: 'tech-news-aggregator-a565b.firebasestorage.app',
    iosBundleId: 'com.example.techsta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM717y_Q9GXXqljQOyJA1-oTQPpI8ae3I',
    appId: '1:908937894285:web:e2588bdbf71fa977d385c4',
    messagingSenderId: '908937894285',
    projectId: 'tech-news-aggregator-a565b',
    authDomain: 'tech-news-aggregator-a565b.firebaseapp.com',
    storageBucket: 'tech-news-aggregator-a565b.firebasestorage.app',
  );
}
